name: ContinousIntegrationMaster

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 6.0.x
          
      - name: Restore depedencies
        run: dotnet restore
        
      - name: Build project
        run: dotnet build --no-restore
        
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
           
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
        
      - name: Build Docker image
        run: docker build -t home-budget:v1 ./Dockerfile
        
      - name: Push Docker image to repository
        run: docker push home-budget:v1
